### ISSUE TITLE
Problems with macro-icons after translation

### ISSUE THREAD

**Issue by ghost** [Phanx/MacroTranslator#1]
After each translation, all the macros changing in red question marks.
To fix that manually, I need to edit the macro-icon to red question mark in the macro menu and save it.
So the right #shwowtooltip icon appears.
This have to be done each time. Is there some possibility to fix that in the addon?

thanks
Benny

**Comment by Phanx** [comment]
Yeah... Can you follow these steps and report back with the results:
1. Type `/run hooksecurefunc("EditMacro", function(...) print(...) end)` in-game and press Enter.
2. If a box pops up warning you about running scripts from strangers, click ok/yes/whatever and repeat step 1.
3. Edit a macro that doesn't currently use the question mark icon, to give it the question mark icon.
4. Screenshot or copy/paste the message that appears in your chat frame.

(The script will make a message will appear every time you edit a macro, showing the values that were passed to the game function that actually saves the macro, until you reload the UI or re-log.)
